.PHONY: clean all

P6AS = ../p6microcode-tools/p6as

#TODO: Enable -Wconversion one day...
CFLAGS += $(CFLAGS-$@) -O2 -Wall -Wextra

CFLAGS-utool = -m32 -static
#TODO: might be handy: -Wl,-Tdata=0xA000

CFLAGS-microload = -m32  -static -O0

CROM_PART =  0 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400 416 432 448 464 480 496

PPRO_DCPUID = 612 619

PII_UCPUID = 634 652 66a
PII_DCPUID = 66a 634 651

#FIXME: This won't work unless correct CRBUS ops are generated by p6as
PIII_UCPUID = 686 6b4
#FIXME: This won't work unless correct CRBUS ops are generated by p6as
PIII_DCPUID = 6b4

PM_UCPUID = 6d8 6d6
PM_DCPUID = 6d6

PPRO_DATS += $(foreach cpuid,$(PPRO_UCPUID),patches/$(cpuid)/utool-$(cpuid).dat)
PPRO_DATS += $(foreach cpuid,$(PPRO_DCPUID),patches/$(cpuid)/msromdumper-$(cpuid).dat)
PPRO_DATS += $(foreach crompart,$(CROM_PART),patches/619/cromdumper-619-$(crompart).dat)
PPRO_DATS += $(foreach crompart,$(CROM_PART),patches/612/cromdumper-612-$(crompart).dat)

PII_DATS += $(foreach cpuid,$(PII_UCPUID),patches/$(cpuid)/utool-$(cpuid).dat)
PII_DATS += $(foreach cpuid,$(PII_DCPUID),patches/$(cpuid)/msromdumper-$(cpuid).dat)
PII_DATS += $(foreach crompart,$(CROM_PART),patches/66a/cromdumper-66a-$(crompart).dat)

PIII_DATS += $(foreach cpuid,$(PIII_UCPUID),patches/$(cpuid)/utool-$(cpuid).dat)
PIII_DATS += $(foreach cpuid,$(PIII_DCPUID),patches/$(cpuid)/msromdumper-$(cpuid).dat)

PM_DATS += $(foreach cpuid,$(PM_UCPUID),patches/$(cpuid)/utool-$(cpuid).dat)
PM_DATS += $(foreach cpuid,$(PM_DCPUID),patches/$(cpuid)/msromdumper-$(cpuid).dat)

DATS = $(PPRO_DATS) $(PII_DATS) $(PIII_DATS) $(PM_DATS)

GENFILES = $(DATS)
GENFILES += $(DATS:.dat=.gen)
GENFILES += $(DATS:.dat=.hex)

UHEX = $(DATS:.dat=.uhex)

EXEC := microload utool msrom2scramble
DOTEXE := $(EXEC:%=%.exe)

$(PPRO_DATS) : EXTRA_OPTS = -t pentiumpro
$(PII_DATS) : EXTRA_OPTS = -t pentium2
$(PIII_DATS) : EXTRA_OPTS = -t pentium3
$(PM_DATS) : EXTRA_OPTS = -t pentiumm
$(PM_DATS) : EXTRA_P6AS_OPTS = -DPENTIUMM

#.precious: $(GENFILES) $(UHEX)

all:  $(EXEC) $(DATS)

microload : microload.c

%.dat: %.txt %.hex
	../patchtools_pub/patchtools -c -p $@ -i $(filter %.txt,$<)

patches/619/msromdumper-619.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID_PPRO -L ROMDUMPER_DONE=0x291d $< > $@

patches/612/msromdumper-612.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID_PPRO -L ROMDUMPER_DONE=0x291d $< > $@

patches/634/msromdumper-634.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID -L ROMDUMPER_DONE=0x09fa $< > $@

patches/634/utool-634.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID_FULL -L CPUID_DONE=0x1401 -L CPUID_OTHER=0x0a0a -L CPUID_SKIP=0x1e21 $< > $@

patches/651/msromdumper-651.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID -L ROMDUMPER_DONE=0x0f5c $< > $@

patches/652/utool-652.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_UJCC -L CPUID_DONE=0x1e15 -L CPUID_OTHER=0x2f10  $< > $@

patches/66a/msromdumper-66a.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_UJCC -L ROMDUMPER_DONE=0x2b7a $< > $@

patches/66a/utool-66a.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_UJCC -L CPUID_DONE=0x1cd1 -L CPUID_OTHER=0x2b8a  $< > $@

#The prologue patches/ucode-exit-pm.txt is unused/can be replaced with nops
patches/686/utool-686.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_SIGEVENT -L CPUID_DONE=0x1b9c -L CPUID_OTHER=0x07be  $< > $@

#FIXME: prologue not needed - keep until .org is fixed
patches/6b4/msromdumper-6b4.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_UJCC -L ROMDUMPER_DONE=0x26ca $< > $@

#The prologue patches/ucode-exit-pm.txt is unused/can be replaced with nops
patches/6b4/utool-6b4.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_SIGEVENT -L CPUID_DONE=0x440 -L CPUID_OTHER=0x26a1  $< > $@

patches/6d6/msromdumper-6d6.uhex: patches/msromdumper.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_SIGEVENT -L ROMDUMPER_DONE=0x1b41 $< > $@

patches/6d6/utool-6d6.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_SIGEVENT -L CPUID_DONE=0x332c -L CPUID_OTHER=0x1b3e  $< > $@

patches/6d8/utool-6d8.uhex: patches/utool.asm
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_SIGEVENT -L CPUID_DONE=0x332c -L CPUID_OTHER=0x1b3e  $< > $@

patches/cromdumper-%.gen: patches/cromdumper.asm
	BASE=$$(($*)) ; \
	START=$$(($$BASE)) ; \
	END=$$(($$START+15)) ; \
	ADDR=$$((0)); \
	echo > $@ ; \
	for i in $$(seq $$START $$END); do \
	HEX=`printf "%03x" $$i` ; \
	HEXA=`printf "%03x" $$ADDR` ; \
	echo "STRD.DSZ32           (CONST_0       , CONSTROM.$$HEX )" >> $@ ; \
	echo "STA.M40.SC1.DSZ64(CONST_04+$$HEXA  , TMP0          , LINSEG  )" >> $@ ; \
	ADDR=$$(($$ADDR+8)) ; \
	done ; \
	echo "MOVETOCREG     (BBL_CR_D3_H    , TMPC)" >> $@ ; \
	echo "U_JMP.NT        ( CONST, ROMDUMPER_DONE, IA.11, U3.1b )" >> $@

patches/66a/cromdumper-66a-%.txt: patches/66a/msromdumper-66a.txt
	sed 's/msromdumper-66a.hex/cromdumper-66a-'$*'.hex/'  $(@D)/msromdumper-66a.txt  > $(@D)/cromdumper-66a-$*.txt

patches/66a/cromdumper-66a-%.gen: patches/cromdumper-%.gen
	cat patches/cromdumper.asm patches/cromdumper-$*.gen > $(@D)/cromdumper-66a-$*.gen

patches/66a/cromdumper-66a-%.uhex: patches/66a/cromdumper-66a-%.gen
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_UJCC -L ROMDUMPER_DONE=0x2b7a $< > $@

patches/612/cromdumper-612-%.txt: patches/612/msromdumper-612.txt
	sed 's/msromdumper-612.hex/cromdumper-612-'$*'.hex/'  $(@D)/msromdumper-612.txt  > $(@D)/cromdumper-612-$*.txt

patches/612/cromdumper-612-%.gen: patches/cromdumper-%.gen
	cat patches/cromdumper.asm patches/cromdumper-$*.gen > $(@D)/cromdumper-612-$*.gen

patches/612/cromdumper-612-%.uhex: patches/612/cromdumper-612-%.gen
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID_PPRO -L ROMDUMPER_DONE=0x291d $< > $@

patches/619/cromdumper-619-%.txt: patches/619/msromdumper-619.txt
	sed 's/msromdumper-619.hex/cromdumper-619-'$*'.hex/'  $(@D)/msromdumper-619.txt  > $(@D)/cromdumper-619-$*.txt

patches/619/cromdumper-619-%.gen: patches/cromdumper-%.gen
	cat patches/cromdumper.asm patches/cromdumper-$*.gen > $(@D)/cromdumper-619-$*.gen

patches/619/cromdumper-619-%.uhex: patches/619/cromdumper-619-%.gen
	$(P6AS) $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) -DPROLOGUE_CPUID_PPRO -L ROMDUMPER_DONE=0x291d $< > $@

#%.uhex : %.gen
#	python ../p6tools/simpleas.py $< > $@
#	../p6microcode-tools/p6as $(EXTRA_OPTS) $(EXTRA_P6AS_OPTS) $< > $@

%.hex : %.uhex
#	python ../p6tools/scramble.py $< > $@
	../p6microcode-tools/p6scrambler $(EXTRA_OPTS) $< > $@

utool : utool.c

msrom2scramble : msrom2scramble.c

clean :
	rm -f $(UHEX) $(GENFILES)$(DOTEXE) $(EXEC)

distclean : clean
	rm -f $(DATS)
